[package]
name = "VoxelGame"
version = "0.1.0"
edition = "2021"

[features]
diagnostic = ["bevy_screen_diagnostics"]

[dependencies]
bevy = "0.13.2"
bevy_screen_diagnostics = { version = "0.5.0", optional = true }
bevy_flycam = "0.13.0"
block-mesh = "0.2.0"